# Generated by Django 5.0.3 on 2024-03-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsBE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bills',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
